### ISSUE TITLE
Reason for adding material 3 when using the library

### ISSUE THREAD

**Issue by kibettheophilus** [Breens-Mbaka/BeeTablesCompose#2]
Hi @Breens-Mbaka , I see on the getting started section that one must add the material3 lib before using...what is the reason behind that?

**Comment by Breens-Mbaka** [comment]
Hi @kibettheophilus I think I shoot myself in the foot there but the table doesn't require Material3 to run, let me remove that step. Thanks for nothing that again, much appreciated

**Comment by Breens-Mbaka** [comment]
> Hi @kibettheophilus I think I shoot myself in the foot there but the table doesn't require Material3 to run, let me remove that step. Thanks for nothing that again, much appreciated

Done ✅, that statement was misleading this library doesn't need someone to add Material3 dependency, sorry for that and once more thanks for spotting that.

**Comment by kibettheophilus** [comment]
> > Hi @kibettheophilus I think I shoot myself in the foot there but the table doesn't require Material3 to run, let me remove that step. Thanks for nothing that again, much appreciated
> 
> Done ✅, that statement was misleading this library doesn't need someone to add Material3 dependency, sorry for that and once more thanks for spotting that.

great

**Comment by kibettheophilus** [comment]
How about this?

<img width="858" alt="Screenshot 2023-07-27 at 20 39 53" src="https://github.com/Breens-Mbaka/BeeTablesCompose/assets/61080898/2a11ac33-55e3-4795-aac0-adb221b8c5e3">

**Comment by Breens-Mbaka** [comment]
Hi @kibettheophilus I removed this yesterday maybe check again
