### ISSUE TITLE
Not able to scroll when I have large data set

### ISSUE THREAD

**Issue by kibettheophilus** [Breens-Mbaka/BeeTablesCompose#9]
**Describe the bug**
When I provide data which goes past the screen, I am not able to scroll down the screen to view all the data... I only see the ones covered on the screen.

**To Reproduce**
1. Go to Sample app, provide a long list of teams that will go past the screen
3. Run the app
4. Try to scroll down to to the last team 

**Expected behavior**
I should be able to scroll and view all my teams

**Screenshots**
<img width="353" alt="Screenshot 2023-07-30 at 16 02 23" src="https://github.com/Breens-Mbaka/BeeTablesCompose/assets/61080898/51a079e9-34a8-4d77-850a-fac4ee0981cc">

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**BeeTablesCompose Library Version**
  - Library version: [1.0.3]

**Additional context**
I am not sure if this should be a bug or a feature request

**Comment by Breens-Mbaka** [comment]
Hi @kibettheophilus thanks for raising this, I think we can consider this to be a bug. I had used a Column and didn't enable it to be scrollable. Do you want to work on the fix? I think the solution is to make the Column scrollable or use a Lazy column.

**Comment by kibettheophilus** [comment]
Hi @Breens-Mbaka , sure...I will pick this up, will let you know incase I need some assistance.

**Comment by Breens-Mbaka** [comment]
Awesome @kibettheophilus, before you create a PR be sure to read this [short guide](https://github.com/Breens-Mbaka/BeeTablesCompose/blob/master/.github/ISSUE_TEMPLATE/pull_request_template.md) incase you didn't. All the best.

**Comment by kibettheophilus** [comment]
> Awesome @kibettheophilus, before you create a PR be sure to read this [short guide](https://github.com/Breens-Mbaka/BeeTablesCompose/blob/master/.github/ISSUE_TEMPLATE/pull_request_template.md) incase you didn't. All the best.

Shouldn't the pull request template be populated when a pull request is opened?
